site_name: Gerenciamento de pacotes no Debian e derivados
site_author: Jurandy Soares

theme:
  name: material
  language: pt
  palette:
    primary: green

nav:
  - index.md
  - agenda.md
  - termos.md
  - pacotes.md
  - repositorios.md
  - dpkg.md
  - apt:
    - Introdução: apt/introducao.md
    - Fonte: apt/fontes.md
    - Listagem: apt/list.md
    - Busca: apt/search.md
    - Exibição: apt/show.md
    - Instalação: apt/install.md
    - Remoção: apt/remove.md
    - Autorremoção: apt/autoremove.md
    - Catálogo: apt/update.md
    - Atualização: apt/upgrade.md
    - Atualização completa: apt/full-upgrade.md
    - Edição das fontes: apt/edit-sources.md
  - snap.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
